// Cloudflare Worker — entry point for the clip-worker service.
// Handles auth (Bearer WORKER_SECRET) then routes to the Container
// instance via Durable Objects (Cloudflare Containers API).

import { Container, getContainer } from "@cloudflare/containers";
import { env } from "cloudflare:workers";

// `Env` is the global interface generated by `wrangler types` into
// worker-configuration.d.ts (from wrangler.jsonc bindings/vars + .dev.vars):
// CLIP_CONTAINER (typed to ClipContainer), R2_*, WORKER_SECRET,
// DEBUG_PHASE_MARKERS. Rerun `wrangler types` after changing bindings/vars.

// Container class — extends Container<Env> (Durable Object backed by Docker image).
// defaultPort must match EXPOSE in Dockerfile and Bun.serve port in server.ts.
// sleepAfter: hibernates the container after inactivity to save cost.
// envVars: injects Worker Secrets into the Container process as process.env.*
export class ClipContainer extends Container<Env> {
  defaultPort = 8080;
  sleepAfter = "20m";
  envVars = {
    R2_ACCOUNT_ID: env.R2_ACCOUNT_ID,
    R2_ACCESS_KEY_ID: env.R2_ACCESS_KEY_ID,
    R2_SECRET_ACCESS_KEY: env.R2_SECRET_ACCESS_KEY,
    R2_BUCKET: env.R2_BUCKET,
    R2_ENDPOINT: env.R2_ENDPOINT,
    WORKER_SECRET: env.WORKER_SECRET,
    // Diagnostic phase breadcrumbs (_ea/_dk/_cl_phase.json) + [timing] logs.
    // Unset/"false" → off (zero R2 overhead). Set to "true" to re-enable.
    DEBUG_PHASE_MARKERS: env.DEBUG_PHASE_MARKERS ?? "false",
  };
}

const START_TIMEOUT_MS = 30_000;

// In-flight readiness lock. Coalesces concurrent requests onto a single
// startAndWaitForPorts() wait so a cold boot isn't stampeded by N parallel
// requests (and so a later request can't reach container.fetch() — which
// triggers the library's request.signal-bound internal wait — before the port
// is actually up). Cleared once settled so the NEXT request re-checks readiness
// (the container may have slept since); when warm, startAndWaitForPorts returns
// immediately, so calling it every request is cheap.
let inflightReady: Promise<void> | null = null;

function waitForContainerReady(
  container: DurableObjectStub<ClipContainer>
): Promise<void> {
  if (inflightReady) return inflightReady;

  // Definite-assignment (`!`): the closure below references `p` in its finally,
  // but that runs asynchronously — after `p` is assigned — so it's safe. The
  // assertion tells TS the variable is assigned before any such use.
  let p!: Promise<void>;
  p = (async () => {
    try {
      await container.startAndWaitForPorts(undefined, {
        instanceGetTimeoutMS: START_TIMEOUT_MS,
        portReadyTimeoutMS: START_TIMEOUT_MS,
      });
    } finally {
      // Clear only if we're still the active wait — don't stomp a newer one.
      if (inflightReady === p) inflightReady = null;
    }
  })();

  inflightReady = p;
  return p;
}

// Constant-time comparison of the Authorization header against the expected
// Bearer secret. Length mismatch fails fast (timingSafeEqual requires equal-
// length buffers); the equal-length path is timing-safe (no early byte exit).
function safeBearerEqual(provided: string | null, expected: string): boolean {
  if (provided === null) return false;
  const a = new TextEncoder().encode(provided);
  const b = new TextEncoder().encode(expected);
  if (a.byteLength !== b.byteLength) return false;
  return crypto.subtle.timingSafeEqual(a, b);
}

export default {
  async fetch(request: Request, env: Env): Promise<Response> {
    // Auth check — all requests must carry the shared secret (timing-safe).
    const auth = request.headers.get("Authorization");
    if (!safeBearerEqual(auth, `Bearer ${env.WORKER_SECRET}`)) {
      return Response.json({ error: "Unauthorized" }, { status: 401 });
    }

    // Buffer the request body NOW, while the edge connection is still alive.
    // During a cold-start wait (below) the original Request gets Canceled at the
    // CF edge, which also kills its body stream. Forwarding the original then —
    // or even rebuilding from request.body — fails ("Canceled") even once the
    // container is up. Capturing the bytes up front lets us rebuild a fresh,
    // detached Request afterwards (and an ArrayBuffer body needs no duplex).
    const method = request.method;
    const url = request.url;
    const headers = new Headers(request.headers);
    const bodyBuffer =
      method !== "GET" && method !== "HEAD"
        ? await request.arrayBuffer()
        : undefined;

    // Use a singleton container named "main".
    // For parallel processing in future, pass videoId as the name to get
    // per-video containers — each clip job gets its own isolated instance.
    const container = getContainer(env.CLIP_CONTAINER, "main");

    // Cold-start fix: ensure the container's port is accepting connections
    // BEFORE forwarding, on EVERY request. Coalesced via the in-flight lock so
    // concurrent requests share one wait. Bounded by a native timeout so a slow
    // cold start fails fast with 503 instead of holding the connection open
    // (an unbounded wait made Next hit UND_ERR_HEADERS_TIMEOUT). The wait itself
    // is not tied to request.signal — a client disconnect must not abort boot.
    try {
      await waitForContainerReady(container);
    } catch {
      return Response.json(
        { error: "Container not ready, retry shortly" },
        { status: 503 }
      );
    }

    // Build a FRESH Request from the buffered bytes — the original is Canceled
    // after the wait. ArrayBuffer body is reusable, so we can rebuild per attempt.
    const buildReq = () =>
      new Request(url, { method, headers, body: bodyBuffer });

    try {
      return await container.fetch(buildReq());
    } catch {
      // Transient race right after boot — the port just came up; retry once.
      await new Promise((r) => setTimeout(r, 500));
      try {
        return await container.fetch(buildReq());
      } catch {
        return Response.json(
          { error: "Container not ready, retry shortly" },
          { status: 503 }
        );
      }
    }
  },

  // Cron Trigger handler — keep-warm. Boots the container if asleep and pings
  // /health so it stays under the sleepAfter window. Best-effort: any failure
  // is swallowed (next tick retries; user requests still cold-start safely via
  // the fetch() readiness logic above).
  async scheduled(_event: ScheduledController, env: Env, ctx: ExecutionContext) {
    ctx.waitUntil(
      (async () => {
        const container = getContainer(env.CLIP_CONTAINER, "main");
        try {
          await container.startAndWaitForPorts();
          await container.fetch(new Request("http://internal/health"));
          console.log("[keep-warm] /health ping ok");
        } catch (e) {
          console.log(
            "[keep-warm] ping failed (best-effort): " +
              (e instanceof Error ? e.message : String(e))
          );
        }
      })()
    );
  },
} satisfies ExportedHandler<Env>;
